# Generated by Django 4.1.1 on 2022-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True, verbose_name='Country name')),
                ('group', models.CharField(max_length=12, verbose_name='Group')),
                ('flag_image', models.ImageField(upload_to='media/flags', verbose_name='Flag image')),
                ('team_code', models.CharField(max_length=3, verbose_name='Team code')),
                ('points', models.IntegerField(default=0, verbose_name='Team points')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Matches played')),
                ('wins', models.IntegerField(default=0, verbose_name='team wins')),
                ('draws', models.IntegerField(default=0, verbose_name='team draws')),
                ('losses', models.IntegerField(default=0, verbose_name='team losses')),
                ('goals_for', models.IntegerField(default=0, verbose_name='Goals for')),
                ('goals_against', models.IntegerField(default=0, verbose_name='Goals against')),
                ('goal_difference', models.IntegerField(default=0, verbose_name='Goal difference')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ['-points', '-goal_difference', '-goals_for'],
            },
        ),
    ]
