# Generated by Django 4.1.1 on 2022-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag_image',
            field=models.ImageField(upload_to='flags', verbose_name='Flag image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.SlugField(max_length=12, unique=True, verbose_name='Team slug'),
        ),
    ]
