# Generated by Django 4.1.1 on 2022-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0002_alter_team_flag_image_alter_team_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='first_place',
            field=models.BooleanField(default=False, verbose_name='First place'),
        ),
        migrations.AddField(
            model_name='team',
            name='second_place',
            field=models.BooleanField(default=False, verbose_name='Second place'),
        ),
    ]
