# Generated by Django 4.1.1 on 2022-10-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0003_team_first_place_team_second_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldcupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_goals', models.IntegerField(default=0, verbose_name='Team 1 goals')),
                ('team_2_goals', models.IntegerField(default=0, verbose_name='Team 2 goals')),
                ('match_number', models.IntegerField(default=0, verbose_name='Match number')),
                ('match_date', models.DateTimeField(verbose_name='Match date')),
                ('round', models.PositiveIntegerField(default=0, verbose_name='Round')),
                ('group', models.CharField(max_length=12, verbose_name='Group')),
                ('started', models.BooleanField(default=False, verbose_name='Match started')),
                ('finished', models.BooleanField(default=False, verbose_name='Match finished')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='worldcup.team', verbose_name='Team 1')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='worldcup.team', verbose_name='Team 2')),
            ],
        ),
    ]
