# Generated by Django 4.1.1 on 2022-10-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldcup', '0005_alter_worldcupmatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_goals', models.IntegerField(default=0, verbose_name='Team 1 goals')),
                ('team_2_goals', models.IntegerField(default=0, verbose_name='Team 2 goals')),
                ('match_number', models.IntegerField(default=0, verbose_name='Match number')),
                ('match_date', models.DateTimeField(verbose_name='Match date')),
                ('round', models.IntegerField(default=0, verbose_name='Round')),
                ('group', models.CharField(max_length=12, verbose_name='Group')),
                ('started', models.BooleanField(default=False, verbose_name='Match started')),
                ('finished', models.BooleanField(default=False, verbose_name='Match finished')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldcup_pool', to='worldcup.worldcuppool', verbose_name='worldcup pool')),
            ],
            options={
                'verbose_name_plural': 'Pools matches',
                'ordering': ['match_number', 'group'],
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='flag_image',
            field=models.ImageField(upload_to='media/flags', verbose_name='Flag image'),
        ),
        migrations.DeleteModel(
            name='PoolsMatch',
        ),
        migrations.AddField(
            model_name='poolmatch',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_pools', to='worldcup.team', verbose_name='Team 1 pools'),
        ),
        migrations.AddField(
            model_name='poolmatch',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_pools', to='worldcup.team', verbose_name='Team 2 pools'),
        ),
        migrations.AddField(
            model_name='poolmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
