# Generated by Django 4.1.1 on 2022-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0006_poolmatch_alter_team_flag_image_delete_poolsmatch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolmatch',
            options={'ordering': ['pool', 'match_number', 'group'], 'verbose_name_plural': 'Pools matches'},
        ),
        migrations.AddField(
            model_name='poolmatch',
            name='pool_match_points',
            field=models.IntegerField(default=0),
        ),
    ]
