# Generated by Django 4.1.1 on 2022-10-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0007_alter_poolmatch_options_poolmatch_pool_match_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolmatch',
            name='analized',
            field=models.BooleanField(default=False, verbose_name='Analised'),
        ),
    ]
