# Generated by Django 4.1.1 on 2022-10-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0008_poolmatch_analized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['group', '-points', 'team_code', '-goals_difference', '-goals_for'], 'verbose_name_plural': 'Teams'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='goal_difference',
            new_name='goals_difference',
        ),
        migrations.AlterField(
            model_name='poolmatch',
            name='analized',
            field=models.BooleanField(default=False, verbose_name='Analized'),
        ),
    ]
