# Generated by Django 4.1.1 on 2022-10-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0009_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['group', '-points', '-goals_difference', 'team_code', '-goals_for'], 'verbose_name_plural': 'Teams'},
        ),
    ]
