# Generated by Django 4.1.1 on 2022-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0011_worldcupkeymatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupmatch',
            name='analized',
            field=models.BooleanField(default=False, verbose_name='worldcup match Analized'),
        ),
    ]
