# Generated by Django 4.1.1 on 2022-11-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0012_worldcupmatch_analized'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupkeymatch',
            name='analized',
            field=models.BooleanField(default=False, verbose_name='key match Analized'),
        ),
    ]
