# Generated by Django 4.1.1 on 2022-11-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0014_alter_worldcupkeymatch_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupkeymatch',
            name='team_loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_loser', to='worldcup.team', verbose_name='Team loser'),
        ),
    ]
