# Generated by Django 4.1.1 on 2022-11-04 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldcup', '0015_worldcupkeymatch_team_loser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolKeyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_goals', models.IntegerField(default=0, verbose_name='Team 1 goals key')),
                ('team_2_goals', models.IntegerField(default=0, verbose_name='Team 2 goals pool key')),
                ('penalties', models.BooleanField(default=False, verbose_name='Penalties pool key')),
                ('team_1_penalty_goals', models.IntegerField(default=0, verbose_name='Team 1 penalty goals')),
                ('team_2_penalty_goals', models.IntegerField(default=0, verbose_name='Team 2 penalty goals')),
                ('round', models.CharField(blank=True, max_length=24, null=True, verbose_name='Round')),
                ('match_number', models.IntegerField(default=0, unique=True, verbose_name='Pool key match number')),
                ('match_date', models.DateTimeField(verbose_name='Key match date')),
                ('started', models.BooleanField(default=False, verbose_name='Pool key match started')),
                ('finished', models.BooleanField(default=False, verbose_name='Pool key match finished')),
                ('analized', models.BooleanField(default=False, verbose_name='Pool key match Analized')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldcup_key_pool', to='worldcup.worldcuppool', verbose_name='worldcup pool key matches')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1_key_pool', to='worldcup.team', verbose_name='Team 1 pool key')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2_key_pool', to='worldcup.team', verbose_name='Team 2 pool key')),
                ('team_loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_loser_pool', to='worldcup.team', verbose_name='Team pool loser')),
                ('team_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_winner_pool', to='worldcup.team', verbose_name='Team pool winner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_key_pool', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Pool key matches',
                'ordering': ['match_number'],
            },
        ),
    ]
