# Generated by Django 4.1.1 on 2022-11-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0016_poolkeymatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolkeymatch',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1_key_pool', to='worldcup.team', verbose_name='Team 1  '),
        ),
        migrations.AlterField(
            model_name='poolkeymatch',
            name='team_1_goals',
            field=models.IntegerField(default=0, verbose_name='Team 1 goals'),
        ),
        migrations.AlterField(
            model_name='poolkeymatch',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2_key_pool', to='worldcup.team', verbose_name='Team 2 '),
        ),
        migrations.AlterField(
            model_name='poolkeymatch',
            name='team_2_goals',
            field=models.IntegerField(default=0, verbose_name='Team 2 goals '),
        ),
    ]
