# Generated by Django 4.1.1 on 2022-11-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0017_alter_poolkeymatch_team_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolkeymatch',
            name='pool_match_points',
            field=models.IntegerField(default=0),
        ),
    ]
