# Generated by Django 4.1.1 on 2022-11-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0018_poolkeymatch_pool_match_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolkeymatch',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Key match date'),
        ),
        migrations.AlterField(
            model_name='poolkeymatch',
            name='match_number',
            field=models.IntegerField(default=0, verbose_name='Pool key match number'),
        ),
    ]
