# Generated by Django 4.1.1 on 2022-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0019_alter_poolkeymatch_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcuppool',
            name='group_points',
            field=models.IntegerField(default=0, verbose_name='Group Points'),
        ),
        migrations.AddField(
            model_name='worldcuppool',
            name='round_group_points',
            field=models.IntegerField(default=0, verbose_name='Group Points'),
        ),
        migrations.AddField(
            model_name='worldcuppool',
            name='round_key_points',
            field=models.IntegerField(default=0, verbose_name='Key Points'),
        ),
    ]
