# Generated by Django 4.1.1 on 2022-11-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0020_worldcuppool_group_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=12, verbose_name='Group')),
                ('pool_team_points', models.IntegerField(default=0, verbose_name='Team points')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Matches played')),
                ('wins', models.IntegerField(default=0, verbose_name='team wins')),
                ('draws', models.IntegerField(default=0, verbose_name='team draws')),
                ('losses', models.IntegerField(default=0, verbose_name='team losses')),
                ('pool_team_goals_for', models.IntegerField(default=0, verbose_name='Goals for')),
                ('pool_team_goals_against', models.IntegerField(default=0, verbose_name='Goals against')),
                ('pool_team_goals_difference', models.IntegerField(default=0, verbose_name='Goal difference')),
                ('first_place', models.BooleanField(default=False, verbose_name='First place')),
                ('second_place', models.BooleanField(default=False, verbose_name='Second place')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_team', to='worldcup.worldcuppool', verbose_name='Pool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_team', to='worldcup.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ['group', '-pool_team_points', '-pool_team_goals_difference', '-pool_team_goals_for'],
            },
        ),
    ]
