# Generated by Django 4.1.1 on 2022-11-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0021_poolteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolteam',
            options={'ordering': ['group', '-pool_team_points', '-pool_team_goals_difference', '-pool_team_goals_for'], 'verbose_name_plural': 'Pool Teams'},
        ),
        migrations.AddField(
            model_name='poolteam',
            name='team_code',
            field=models.SlugField(default=None, max_length=12, unique=True, verbose_name='Team slug'),
            preserve_default=False,
        ),
    ]
