# Generated by Django 4.1.1 on 2022-11-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0023_alter_poolkeymatch_analized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcuppool',
            name='group_analized',
            field=models.BooleanField(default=False, verbose_name='Group Analized'),
        ),
    ]
